# Generated by Django 4.0.4 on 2022-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggits', '0002_entry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
